config/routes.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

Diaspora::Application.routes.draw do
  resources :status_messages, :only   => [:create, :destroy, :show]
  resources :comments,        :except => [:index]
  resources :requests,        :except => [:edit, :update]
  resources :photos,          :except => [:index]
  resources :services

  resources :people
  resources :people do
    resources :status_messages
    resources :photos
  end
  match '/people/by_handle' => 'people#retrieve_remote', :as => 'person_by_handle'

  match '/auth/:provider/callback' => 'services#create'

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :password      => "devise/passwords",
                                      :invitations   => "invitations"}
  # added public route to user
  match 'public/:username',          :to => 'users#public'
  match 'getting_started',           :to => 'users#getting_started', :as => 'getting_started'
  match 'users/export',              :to => 'users#export'
  match 'users/export_photos',       :to => 'users#export_photos'
  match 'login',                     :to => 'users#sign_up'
  resources :users,                  :except => [:create, :new, :show]

  match 'aspects/move_contact',  :to => 'aspects#move_contact', :as => 'move_contact'
  match 'aspects/add_to_aspect',:to => 'aspects#add_to_aspect', :as => 'add_to_aspect'
  match 'aspects/remove_from_aspect',:to => 'aspects#remove_from_aspect', :as => 'remove_from_aspect'
  match 'aspects/manage',       :to => 'aspects#manage'
  resources :aspects,           :except => [:edit]

  #match 'warzombie',          :to   => "dev_utilities#warzombie"
  #match 'zombiefriends',      :to   => "dev_utilities#zombiefriends"
  #match 'zombiefriendaccept', :to   => "dev_utilities#zombiefriendaccept"
  #match 'set_backer_number',  :to   => "dev_utilities#set_backer_number"
  #match 'set_profile_photo',  :to   => "dev_utilities#set_profile_photo"

  #public routes
  match 'webfinger',            :to => 'publics#webfinger'
  match 'hcard/users/:id',      :to => 'publics#hcard'
  match '.well-known/host-meta',:to => 'publics#host_meta'
  match 'receive/users/:id',    :to => 'publics#receive'
  match 'hub',                  :to => 'publics#hub'
  #match 'log',                  :to => "dev_utilities#log"


  #root
  root :to => 'home#show'
end

app/models/user.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

require File.join(Rails.root, 'lib/diaspora/user')
require File.join(Rails.root, 'lib/salmon/salmon')

class User
  include MongoMapper::Document
  include Diaspora::UserModules
  include Encryptor::Private

  plugin MongoMapper::Devise

  QUEUE = MessageHandler.new

  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  key :username
  key :serialized_private_key, String
  key :invites, Integer, :default => 5
  key :invitation_token, String
  key :invitation_sent_at, DateTime
  key :pending_request_ids, Array, :typecast => 'ObjectId'
  key :visible_post_ids, Array, :typecast => 'ObjectId'
  key :visible_person_ids, Array, :typecast => 'ObjectId'

  key :getting_started, Boolean, :default => true

  key :language, String

  before_validation :strip_and_downcase_username, :on => :create
  before_validation :set_current_language, :on => :create

  validates_presence_of :username
  validates_uniqueness_of :username, :case_sensitive => false
  validates_format_of :username, :with => /\A[A-Za-z0-9_.]+\z/
  validates_length_of :username, :maximum => 32
  validates_inclusion_of :language, :in => AVAILABLE_LANGUAGE_CODES

  validates_presence_of :person, :unless => proc {|user| user.invitation_token.present?}
  validates_associated :person

  one :person, :class => Person, :foreign_key => :owner_id

  many :invitations_from_me, :class => Invitation, :foreign_key => :from_id
  many :invitations_to_me, :class => Invitation, :foreign_key => :to_id
  many :contacts, :class => Contact, :foreign_key => :user_id
  many :visible_people, :in => :visible_person_ids, :class => Person # One of these needs to go
  many :pending_requests, :in => :pending_request_ids, :class => Request
  many :raw_visible_posts, :in => :visible_post_ids, :class => Post
  many :aspects, :class => Aspect, :dependent => :destroy

  many :services, :class => Service

  #after_create :seed_aspects

  before_destroy :disconnect_everyone, :remove_person
  before_save do
    person.save if person
  end

  attr_accessible :getting_started, :password, :password_confirmation, :language,

  def strip_and_downcase_username
    if username.present?
      username.strip!
      username.downcase!
    end
  end

  def set_current_language
    self.language = I18n.locale.to_s if self.language.blank?
  end

  def self.find_for_authentication(conditions={})
    if conditions[:username] =~ /^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i # email regex
      conditions[:email] = conditions.delete(:username)
    end
    super
  end

  def has_incoming_request_from(person)
    self.pending_requests.select do |req|
      req.to_id == self.person.id
    end.any? { |req| req.from_id == person.id }
  end

  ######## Making things work ########
  key :email, String

  def method_missing(method, *args)
    self.person.send(method, *args) if self.person
  end

  ######### Aspects ######################
  def drop_aspect(aspect)
    if aspect.contacts.count == 0
      aspect.destroy
    else
      raise "Aspect not empty"
    end
  end

  def move_contact(opts = {})
    if opts[:to] == opts[:from]
      true
    elsif opts[:person_id] && opts[:to] && opts[:from]
      from_aspect = self.aspects.find_by_id(opts[:from])

      if add_person_to_aspect(opts[:person_id], opts[:to])
        delete_person_from_aspect(opts[:person_id], opts[:from])
      end
    end
  end

  def add_person_to_aspect(person_id, aspect_id)
    contact = contact_for(Person.find(person_id))
    raise "Can not add person to an aspect you do not own" unless aspect = self.aspects.find_by_id(aspect_id)
    raise "Can not add person you are not connected to" unless contact
    raise 'Can not add person who is already in the aspect' if aspect.contacts.include?(contact)
    contact.aspects << aspect
    contact.save!
    aspect.save!
  end

  def delete_person_from_aspect(person_id, aspect_id, opts = {})
    aspect = Aspect.find(aspect_id)
    raise "Can not delete a person from an aspect you do not own" unless aspect.user == self
    contact = contact_for Person.find(person_id)

    if opts[:force] || contact.aspect_ids.count > 1
      contact.aspect_ids.delete aspect.id
      contact.save!
      aspect.save!
    else
      raise "Can not delete a person from last aspect"
    end
  end

  ######## Posting ########
  def post(class_name, opts = {})
    post = build_post(class_name, opts)

    if post.save
      raise 'MongoMapper failed to catch a failed save' unless post.id
      dispatch_post(post, :to => opts[:to])
    end
    post
  end

  def build_post(class_name, opts = {})
    opts[:person] = self.person
    opts[:diaspora_handle] = opts[:person].diaspora_handle

    model_class = class_name.to_s.camelize.constantize
    model_class.instantiate(opts)
  end

  def dispatch_post(post, opts = {})
    aspect_ids = opts.delete(:to)

    aspect_ids = validate_aspect_permissions(aspect_ids)
    self.raw_visible_posts << post
    self.save

    #socket post
    Rails.logger.info("event=dispatch user=#{diaspora_handle} post=#{post.id.to_s}")
    push_to_aspects(post, aspect_ids)
    post.socket_to_uid(id, :aspect_ids => aspect_ids) if post.respond_to?(:socket_to_uid) && !post.pending

    if post.public
      self.services.each do |service|
        self.send("post_to_#{service.provider}".to_sym, service, post.message)
      end
    end
  end

  def post_to_facebook(service, message)
    Rails.logger.info("Sending a message: #{message} to Facebook")
    EventMachine::HttpRequest.new("https://graph.facebook.com/me/feed?message=#{message}&access_token=#{service.access_token}").post
  end

  def post_to_twitter(service, message)
    oauth = Twitter::OAuth.new(SERVICES['twitter']['consumer_token'], SERVICES['twitter']['consumer_secret'])
    oauth.authorize_from_access(service.access_token, service.access_secret)
    client = Twitter::Base.new(oauth)
    client.update(message)
  end

  def update_post(post, post_hash = {})
    if self.owns? post
      post.update_attributes(post_hash)
      aspects = aspects_with_post(post.id)
      self.push_to_aspects(post, aspects)
    end
  end

  def validate_aspect_permissions(aspect_ids)
    if aspect_ids == "all"
      return aspect_ids
    end

    aspect_ids = [aspect_ids.to_s] unless aspect_ids.is_a? Array

    if aspect_ids.nil? || aspect_ids.empty?
      raise ArgumentError.new("You must post to someone.")
    end

    aspect_ids.each do |aspect_id|
      unless self.aspects.find(aspect_id)
        raise ArgumentError.new("Cannot post to an aspect you do not own.")
      end
    end

    aspect_ids
  end

  def push_to_aspects(post, aspect_ids)
    if aspect_ids == :all || aspect_ids == "all"
      aspects = self.aspects
    elsif aspect_ids.is_a?(Array) && aspect_ids.first.class == Aspect
      aspects = aspect_ids
    else
      aspects = self.aspects.find_all_by_id(aspect_ids)
    end
    #send to the aspects
    target_contacts = []

    aspects.each { |aspect|
      aspect.posts << post
      aspect.save
      target_contacts = target_contacts | aspect.contacts
    }

    push_to_hub(post) if post.respond_to?(:public) && post.public

    push_to_people(post, self.person_objects(target_contacts))
  end

  def push_to_people(post, people)
    salmon = salmon(post)
    people.each do |person|
      push_to_person(salmon, post, person)
    end
  end

  def push_to_person(salmon, post, person)
    person.reload # Sadly, we need this for Ruby 1.9.
    # person.owner will always return a ProxyObject.
    # calling nil? performs a necessary evaluation.
    unless person.owner.nil?
      Rails.logger.info("event=push_to_person route=local sender=#{self.diaspora_handle} recipient=#{person.diaspora_handle} payload_type=#{post.class}")
      person.owner.receive(post.to_diaspora_xml, self.person)
    else
      xml = salmon.xml_for person
      Rails.logger.info("event=push_to_person route=remote sender=#{self.diaspora_handle} recipient=#{person.diaspora_handle} payload_type=#{post.class}")
      QUEUE.add_post_request(person.receive_url, xml)
      QUEUE.process
    end
  end

  def push_to_hub(post)
    Rails.logger.debug("event=push_to_hub target=#{APP_CONFIG[:pubsub_server]} sender_url=#{self.public_url}")
    QUEUE.add_hub_notification(APP_CONFIG[:pubsub_server], self.public_url)
  end

  def salmon(post)
    created_salmon = Salmon::SalmonSlap.create(self, post.to_diaspora_xml)
    created_salmon
  end

  ######## Commenting  ########
  def comment(text, options = {})
    comment = build_comment(text, options)

    if comment.save
      raise 'MongoMapper failed to catch a failed save' unless comment.id
      dispatch_comment comment
    end
    comment
  end

  def build_comment(text, options = {})
    comment = Comment.new(:person_id => self.person.id,
                          :diaspora_handle => self.person.diaspora_handle,
                          :text => text,
                          :post => options[:on])

    #sign comment as commenter
    comment.creator_signature = comment.sign_with_key(self.encryption_key)

    if !comment.post_id.blank? && owns?(comment.post)
      #sign comment as post owner
      comment.post_creator_signature = comment.sign_with_key(self.encryption_key)
    end

    comment
  end

  def dispatch_comment(comment)
    if owns? comment.post
      #push DOWNSTREAM (to original audience)
      Rails.logger.info "event=dispatch_comment direction=downstream user=#{self.diaspora_handle} comment=#{comment.id}"
      aspects = aspects_with_post(comment.post_id)
    
      #just socket to local users, as the comment has already
      #been associated and saved by post owner
      #  (we'll push to all of their aspects for now, the comment won't
      #   show up via js where corresponding posts are not present)

app/controllers/users_controller.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

class UsersController < ApplicationController
  require File.join(Rails.root, 'lib/diaspora/ostatus_builder')
  require File.join(Rails.root, 'lib/diaspora/exporter')
  require File.join(Rails.root, 'lib/collect_user_photos')

  before_filter :authenticate_user!, :except => [:new, :create, :public]

  respond_to :html

  def edit
    @aspect = :user_edit
    @user   = current_user
  end

  def update
    @user = current_user

    if params[:user][:getting_started]
      boolean = params[:user][:getting_started] == "true"
      @user.update_attributes( :getting_started => boolean )
      redirect_to root_path

    else
      params[:user].delete(:password) if params[:user][:password].blank?
      params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
      params[:user].delete(:language) if params[:user][:language].blank?

      if params[:user][:password] && params[:user][:password_confirmation]
        if @user.update_attributes(:password => params[:user][:password], :password_confirmation => params[:user][:password_confirmation])
          flash[:notice] = I18n.t 'users.update.password_changed'
        else
          flash[:error] = I18n.t 'users.update.password_not_changed'
        end
      elsif params[:user][:language]
        if @user.update_attributes(:language => params[:user][:language])
          flash[:notice] = I18n.t 'users.update.language_changed'
        else
          flash[:error] = I18n.t 'users.update.language_not_changed'
        end
      end

      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    current_user.destroy
    sign_out current_user
    flash[:notice] = I18n.t 'users.destroy'
    redirect_to root_path
  end

  def public
    user = User.find_by_username(params[:username])

    if user
      director = Diaspora::Director.new
      ostatus_builder = Diaspora::OstatusBuilder.new(user)

      render :xml => director.build(ostatus_builder), :content_type => 'application/atom+xml'
    else
      flash[:error] = I18n.t 'users.public.does_not_exist', :username => params[:username]
      redirect_to root_url
    end
  end

  def getting_started
    @aspect   = :getting_started
    @user     = current_user
    @person   = @user.person
    @profile  = @user.profile
    @services = @user.services
    @requests = @user.pending_requests

    @step = ((params[:step].to_i>0)&&(params[:step].to_i<5)) ? params[:step].to_i : 1
    @step ||= 1

    if @step == 4
      @user.getting_started = false
      @user.save
    end
    render "users/getting_started"
  end

  def export
    exporter = Diaspora::Exporter.new(Diaspora::Exporters::XML)
    send_data exporter.execute(current_user), :filename => "#{current_user.username}_diaspora_data.xml", :type => :xml
  end

  def export_photos
    tar_path = PhotoMover::move_photos(current_user)
    send_data( File.open(tar_path).read, :filename => "#{current_user.id}.tar" )
  end
end

app/helpers/users_helper.rb
#   Copyright (c) 2010, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

module UsersHelper
  def first_name_or_username (user)
    set_name = user.person.profile.first_name
    (set_name.nil? || set_name.empty?) ? user.username : user.person.profile.first_name 
  end
end

app/views/users/getting_started/_step_1.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


= form_for @person, :html => { :multipart => true } do |person|
  %h3
    = t('people.edit.your_profile')
    .description
      = t('people.edit.info_available_to')

  = person.error_messages

  = person.fields_for :profile do |profile|
    %h4
      = t('people.edit.your_name')
      = profile.text_field :first_name, :value => @profile.first_name, :placeholder => t('people.edit.first_name')
      = profile.text_field :last_name, :value => @profile.last_name, :placeholder => t('people.edit.last_name')

    %h4
      = t('people.edit.your_gender')
      %br
      = profile.text_field :gender, :value => @profile.gender, :placeholder => t("fill_me_out")

    %h4
      = t('people.edit.your_birthday')
      %br
      = select_date @person.profile.birthday, :prompt => true, :default => true, :order => t('date.order'), :start_year => 2000, :end_year => 1930

    %h4
      = t('people.edit.your_bio')
      = profile.text_area :bio, :value => @profile.bio, :rows => 5, :placeholder => t('fill_me_out')

    %h4
      = t('people.edit.your_photo')
      = render 'people/profile_photo_upload', :form => profile

    %h4
      = t('search')
      %p{:class=>"checkbox_select"}
        = profile.label :searchable, t('people.edit.allow_search')
        = profile.check_box :searchable, {:checked => @person.profile.searchable}, true, false

    = hidden_field_tag :getting_started, @step

  .submit_block
    = person.submit "#{t('users.getting_started.save_and_continue')} →"

app/views/users/getting_started/_step_2.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.
- content_for :head do
  = include_javascripts :aspects

%h3
  = t('.your_aspects')
  .description
    = t('.description')

%h3
  = t('.your_inviter')

%h3
  %ul.dropzone
    - if @requests.size < 1
      %li=t('.no_requests')
    - else
      - for request in @requests
        %li.person.request{:data=>{:guid=>request.id, :person_id=>request.from.id}}
          = person_image_link(request.from)
  .requests
    %p= "#{t('.drag_to_add')} =>"


%ul#aspect_list
  - for aspect in @aspects
    %li.aspect{:data=>{:guid=>aspect.id}}

      .aspect_name
        %span.edit_name_field
          %h3{:contenteditable=>true}
            = aspect.name
          %span.tip click to edit

        %ul.tools
          %li!= remove_link(aspect)

      %ul.dropzone{:data=>{:aspect_id=>aspect.id}}
        -for contact in aspect.contacts
          %li.person{:data=>{:guid=>contact.person.id, :aspect_id=>aspect.id}}
            .delete
              .x
                X
              .circle
            = person_image_link(contact.person)
%h4
  = t('.aspect_name')
  = form_for Aspect.new do |aspect|
    = aspect.text_field :name, :style => "display:inline;"
    = aspect.submit t('.add')
%br
%br

.submit_block
  = link_to "#{t('users.getting_started.save_and_continue')} →", getting_started_path(:step => 3), :class => "button"

app/views/users/getting_started/_step_3.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


%h3
  = t('.your_services')
  .description
    = t('.description')
%ul.stream#service_stream
  - for service in @services
    %h3
      %b= service.provider
      = t('services.index.logged_in_as')
      %b= service.nickname
      = link_to t('services.index.disconnect'), service, :confirm => t('services.index.really_disconnect', :service => service.provider), :method => :delete

%h4= link_to t('services.index.connect_to_twitter'), "/auth/twitter" if SERVICES['twitter']['consumer_key']!= ""
%h4= link_to t('services.index.connect_to_facebook'), "/auth/facebook" if SERVICES['facebook']['app_id'] !=""

.submit_block
  = link_to "#{t('users.getting_started.save_and_continue')} →", getting_started_path(:step => 4), :class => "button"

app/views/users/getting_started/_step_4.html.haml
-#   Copyright (c) 2010, Diaspora Inc.  This file is
-#   licensed under the Affero General Public License version 3 or later.  See
-#   the COPYRIGHT file.


%h1
  = t('.set_up', :name => first_name_or_username(current_user))
  .description
    = t('.ready_to_share')
    %ul.inline_aspect_listing
      - for aspect in @aspects
        %li= aspect

%br
%br

%h3
  = link_to t('.continue'), root_path

%br
%br
%br

%p
  = t('.change_profile')
  = t('.user_menu')

%p
  = t('.manage_aspects')

.submit_block
  = link_to "#{t('.finish')} →", root_url, :class => "button"